### ISSUE TITLE
Couldn't open CopyPasta2\libs\LibStrataFix\lib.xml

### ISSUE THREAD

**Issue by b-morgan** [MChambers1992/CopyPasta2#2]
I'm using CopyPasta2.zip created 10/19 at 08:22

**Comment by MChambers1992** [comment]
This is fixed as per the 1.0.2 release which was this commit https://github.com/MChambers1992/CopyPasta2/commit/ceeb12fd3e0fd798070e44f629fdf16bbada0cf7#diff-c17bbd35f589b7b97001ad3fc15e97d5bc51672e2ea9b7169fe8a548bc67a3ae I removed the LibStrataFix lib entirely as it was causing conflict issues and is no longer required. Latest release build from the repo should be working as expected.

Tukui release also reflects this change as this issue was raised there as well https://www.tukui.org/addons.php?id=186

**Comment by b-morgan** [comment]
Then I'm not getting the .zip file from the right place. On github I go to <>Code, Release and download that .zip, I go to Tukui (link in README.MD) and download that .zip and they are both identical to the .zip I downloaded before which exhibits this issue.

Everything I've downloaded has `## Version: @project-version@` in the .toc file

**Comment by enolgor** [comment]
I think [this line](https://github.com/MChambers1992/CopyPasta2/blob/ceeb12fd3e0fd798070e44f629fdf16bbada0cf7/CopyPasta2/embeds.xml#L11) is the one causing problems. I have the same problem too.

**Comment by b-morgan** [comment]
@enolgor, I believe you are correct. The current version of the .toc file in this git repository has that line removed.

**Comment by MChambers1992** [comment]
Sorry about that @enolgor is correct the embeds was still referencing the now removed LibStrataFix. This is fixed in the latest zip release build and code. Let me know if you are still seeing the issue with the latest release please.

As a side note it looks like the automatic versioning in the toc file isn't quite working correctly either I'll look into that.

**Comment by enolgor** [comment]
It works well now, you can close the issue 👍 

As a side note, I too have sadly to maintain a parallel version of an addon that the original author is missing in action, and my approach for releases is with Github actions, you can check the workflow [here](https://github.com/enolgor/wow-addon-tiptac/blob/master/.github/workflows/release.yml) in case it is for some help.

Thanks for your work!

**Comment by MChambers1992** [comment]
Thanks for the tip @enolgor I'll check that workflow out. Glad its resolved, closing this issue.
